header:
  license:
    spdx-id: EPL-2.0
    copyright-owner: Data In Motion Consutling GmbH
    copyright-year: '2024'
    content: |
      Copyright (c) 2012 - 2024 Data In Motion and others.
      All rights reserved. 
      
      This program and the accompanying materials are made
      available under the terms of the Eclipse Public License 2.0
      which is available at https://www.eclipse.org/legal/epl-2.0/
      SPDX-License-Identifier: EPL-2.0
      
      Contributors:
          Data In Motion - initial API and implementation
    pattern: |
      This program and the accompanying materials are made
      available under the terms of the Eclipse Public License 2.0
      which is available at https://www.eclipse.org/legal/epl-2.0/

  paths:
    - '**/*.java'
  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/package-info.java'
    - '**/packageinfo'
    - '**/module-info.java'
    - '**/*.log'
    - '**/*.txt'
    - '**/*.bnd'
    - '**/*.setup'
    - '**/*.bndrun'
    - '**/*.xml'
    - '**/*.xmi'
    - '**/*.ecore'
    - '**/*.genmodel'
    - '**/*.md'
    - '**/*.MD'
    - '**/*.json'
    - '**/.keep'
    - '**/*.jetproperties'
    - '**/*.javajet'
    - '**/*.javajetinc'
    - '**/*.properties'
    - '**/*.maven'
    - '**/*.mvn'
    - '**/*.html'
    - '**/*.ftl'
    - '**/*.aird'
    - '**/*.basic'
    - '**/*.target'
    - '**/.classpath'
    - 'org.gecko.emf.osgi.codegen/src/org/gecko/emf/osgi/codegen/templates/model/*'
    - 'org.gecko.emf.osgi.extender/src/org/gecko/emf/osgi/extender/**'
    - 'LICENSE'
    - 'Jenkinsfile'
    - 'NOTICE'
    - '.gitattributes'
    - '.github/**'
    - '.gitignore'
    - 'cnf/release/**.*'
    - 'cnf/local/**.*'
    - '.gradle-wrapper/gradle-wrapper.properties'
    - '.licenserc.yaml'
    - '**/.project'
    - '**/*.prefs'
    - 'build.gradle'
    - 'gradle.properties'
    - 'gradlew'
    - 'gradlew.bat'
    - 'settings.gradle'
 
  comment: always
