<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="service" nsURI="http://jena.de/service/1.0" nsPrefix="service">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="de.jena.service.remote"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDescription">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An abstract service description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The identifier for the service provider"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="application/csv"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lifeCycleState" eType="#//ServiceLifeCycleState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//ServiceOperationDescription" containment="true" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceLifeCycleState">
    <eLiterals name="ANNOUNCE"/>
    <eLiterals name="CHANGE" value="1"/>
    <eLiterals name="REMOVE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceOperationDescription">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A response object containing all information about a result and its meta data"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The correlated request id, this reponse belongs to."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationRequestUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Uri to listen "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationResponseUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoveryProviderService">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Method to announce a service providing a service description and a corresponding service lifecycle. This needs to implemented by a service provider.&#xA;&#xA;New service description or their changes or removals should published to topic&#xA;&lt;prefix>/services"/>
    </eAnnotations>
    <eOperations name="announce">
      <eParameters name="description" lowerBound="1" eType="#//ServiceDescription"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoveryConsumerService">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The consumer side to retrieve a service description. Service consumer implement this interface, to listen for service changes.&#xA;&#xA;Consumers should listen to topic:&#xA;&lt;prefix>/services&#xA;to get informed about service descriptions"/>
    </eAnnotations>
    <eOperations name="onServiceAnnounced">
      <eParameters name="description" lowerBound="1" eType="#//ServiceDescription"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
