<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chirpstack" nsURI="https://model.data.jena.de/sensinact/chirpstack/1.0"
    nsPrefix="chirpstack">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Dragino" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="Dragino_LSE01"/>
      <details key="profileId" value="37cf9cbd-e7e1-4269-8c22-b46bb5261a2a"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soil" eType="#//Soil" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" eType="#//Device"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="battery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/BatV"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iflag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/i_flag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sflag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/s_flag"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/Mod"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatureDS18B20" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="mapping">
        <details key="path" value="object/temp_DS18B20"/>
        <details key="type" value="float"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Soil" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/temp_SOIL_f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="water" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/water_SOIL_f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conduct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/conduct_SOIL_f"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DevEUI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/devEui"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/deviceName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/deviceProfileId"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/deviceProfileName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenantId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/tenantId"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenantName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/tenantName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/applicationId"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="deviceInfo/applicationName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SenseCapS2120" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="SenseCAP_S2120_8-in-1_LoRaWAN_Wetterstation"/>
      <details key="profileName" value="SenseCAP S2120 8-in-1 LoRaWAN Wetterstation"/>
      <details key="profileId" value="d03f1299-95a3-4ab2-a924-e0e5fe3b277d"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="air" eType="#//Air" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rain" eType="#//Rain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="light" eType="#//Light"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SenseCapS2105" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="SenseCAP_S2105-LoRaWAN_Soil_Moisture_Temperature_and_EC_Sensor"/>
      <details key="profileName" value="SenseCAP S2105-LoRaWAN® Soil Moisture, Temperature and EC Sensor"/>
      <details key="profileId" value="f74bb315-56ca-48c0-82f8-f7b837f4d917"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="air" eType="#//Air" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rain" eType="#//Rain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="light" eType="#//Light"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SenseCap" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="SenseCAP_Wetterstation_2_0"/>
      <details key="profileName" value="SenseCAP Wetterstation 2.0"/>
      <details key="profileId" value="b6a1cea0-c82d-4261-b32c-cf4d2e1f97fb"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="air" eType="#//Air" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rain" eType="#//Rain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="light" eType="#//Light"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Air" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="airTemperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/0/0/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="airHumidity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/0/1/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="barometricPressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/1/2/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="peakWindGust" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/2/0/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/0/4/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windDirectionSensor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/1/0/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rain" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rainGauge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/1/1/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rainAccumulation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/2/1/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Light" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lightIntensity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/0/2/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uvIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/messages/0/3/measurementValue"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TEKTELIC" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="TEKTELIC_KIWI_Agriculture_Sensor"/>
      <details key="profileName" value="TEKTELIC KIWI Agriculture Sensor"/>
      <details key="profileId" value="93f37439-1425-4a5f-a7e7-7eb4b75f1936"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soil" eType="#//TSoil"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TSoil" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soilWaterTension1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/soil_water_tension1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soilWaterTension2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/soil_water_tension2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soilMoistureRaw1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/soil_moisture_raw1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soilMoistureRaw2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/soil_moisture_raw2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ambientLight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/ambient_light"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EM310" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="EM310-UDL"/>
      <details key="profileId" value="1e6d47f7-1432-4c83-b48d-dd34a7e5e9c6"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trash" eType="#//Trash"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trash" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/distance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="mapping">
        <details key="path" value="object/position"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="battery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/battery"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SN50" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="SN50v3-LB_LS"/>
      <details key="profileName" value="SN50v3-LB/LS"/>
      <details key="profileId" value="a610241d-86c3-4d4a-af88-bfa1754f1610"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//SN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SN" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adc1v" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/ADC1_V"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="battery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/BatV"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adc2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/ADC2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adc3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/ADC3"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolidosTeros21" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Provider">
    <eAnnotations source="model">
      <details key="name" value="Solidos_Teros21"/>
      <details key="profileName" value="Solidos Teros21"/>
      <details key="profileId" value="7022e9ce-7673-4d0c-b3d1-ed51afc3fe27"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Teros21"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Teros21" eSuperTypes="../../org.eclipse.sensinact.gateway.core.models.provider/model/sensinact.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="potentialWater1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/potentialwater_1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="potentialWater2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/potentialwater_2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatur1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/temp_1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatur2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/temp_2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="battery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="mapping">
        <details key="path" value="object/battery_voltage"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
