name: CI Build
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '.github/**/*docs*'
    - '.github/**/*codeql*'
    - '.github/*.yml'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '.github/**/*docs*'
    - '.github/**/*codeql*'
    - '.github/*.yml'

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: >-
    -Dorg.gradle.parallel=true
    -Xms4048m -Xmx4048m -XX:MaxMetaspaceSize=2048m

defaults:
  run:
    shell: bash

jobs:
  Build_Matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
    name: JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v3
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      working-directory: backend  
      run: chmod +x ./gradlew
    - name: Gradle version
      working-directory: backend  
      run: ./gradlew --no-daemon --version
    - name: Build with Gradle
      working-directory: backend  
      run: ./gradlew clean build -x testOSGi -x test
    - name: Upload Test Reports
      if: ${{ always() && ((steps.build.outcome == 'success') || (steps.build.outcome == 'failure')) }}
      uses: actions/upload-artifact@v4
      with:
        name: JDK${{ matrix.java }}_${{ matrix.os }}-test-reports
        path: |
          */generated/test-reports/**/TEST-*.xml

